Add terrain types for all biomes
FAForever/Neroxis-Map-Generator pull request #323
Opened 2023-01-30 12:10 UTC by BlackYps

I fixed the symmetry problem, but not in a good way I think. It's probaby better to have a setSize method that doesn't meddle with the symmetry, but I don't understand that method and the surrounding code enough to do that.

2023-03-04 17:03 UTC, Sheikah45 requested changes

2023-03-04 17:03 UTC, Sheikah45 commented on generator/src/main/java/com/faforever/neroxis/generator/texture/BasicTextureGenerator.java
> +        rockTexture.setSymmetrySettings(noSymmetry);
The symmetry should be set at construction

2023-03-12 03:56 UTC, Sheikah45 commented on shared/src/main/java/com/faforever/neroxis/mask/Mask.java
>      protected SymmetrySettings symmetrySettings;
The symmetrySettings should be marked final so no setter

2023-03-12 12:05 UTC, BlackYps commented
Should be good now

2023-03-12 13:23 UTC, Sheikah45 submitted a review, later dismissed

2023-03-12 14:06 UTC, Sheikah45 approved these changes

2023-03-12 14:06 UTC, merged