Set cubemaps from biome
FAForever/Neroxis-Map-Generator pull request #324
Opened 2023-02-03 18:18 UTC by BlackYps

2023-03-23 22:39 UTC, Sheikah45 requested changes
CubeMaps should not be set in the texture generator. They are already included in the biome which is a member of the scmap already. So if they can be set directly in the SCMap constructor.

Although really looking at this I think it may be better to just have the cubemaps directly in the biome and serialize and deserialize them. Rather than having the name and path separate.

2023-03-23 23:09 UTC, BlackYps commented
So how would I do that? How exactly should they be stored in the biome?

2023-03-23 23:12 UTC, BlackYps commented
It sounds similar to what I did in the first commit

2023-03-23 23:38 UTC, BlackYps commented
I think I got it

2023-03-23 23:55 UTC, Sheikah45 requested changes

2023-03-23 23:55 UTC, Sheikah45 commented on shared/src/main/java/com/faforever/neroxis/map/SCMap.java
> +        }
Since the biome contains the cubeMaps we can remove the addCubeMap method and just use the ones embedded in the biome for import and export

2023-03-24 13:29 UTC, Sheikah45 requested changes

2023-03-24 13:29 UTC, Sheikah45 commented on shared/src/main/java/com/faforever/neroxis/util/serial/biome/TerrainMaterials.java
> +    private List<CubeMap> cubeMaps;
This should be initialized otherwise the importer will throw a null pointer exception

2023-03-25 12:35 UTC, BlackYps commented
lol, the build fails now, but I don't understand why that commit could break it and it works locally on my machine...

2023-03-26 15:13 UTC, Sheikah45 approved these changes

2023-03-26 15:13 UTC, merged