Add Licence
FAForever/Neroxis-Map-Generator pull request #34
Opened 2020-06-16 22:54 UTC by axel1200

Took my name as I was not sure if u wanna be mentioned with your real name. 

Please confirm you wanna add MIT Liscene to this project.

2020-06-17 17:33 UTC, n3roxis commented
I think using my real name is appropriate. You can do so.

2020-06-17 18:27 UTC, n3roxis requested changes

2020-06-17 18:27 UTC, n3roxis commented on LICENSE
> +Copyright (c) 2020 Alexander von Trostorff
Copyright (c) 2020 Peter Ziegler

2020-06-18 13:01 UTC, axel1200 commented
@Geosearchef @Rackover a small message that u are ok with that would be awesome :D

2020-06-18 13:13 UTC, Rackover commented
We can have multiple names on the license, so I do not mind wether or not only Neroxis' name is credited or if we put our three/four names on the License. I think it is up to Neroxis to decide.

Also, you do not need my permission to do something for FAF 😛
Please stop pinging me, my mail box is already getting a lot of notifications from FAF github that I must disable every time independantly. 

If you need my name for credits purposes, use Roxanne De Louvegarde <rackover@racknet.noip.me>

2020-06-20 14:41 UTC, axel1200 commented
Sure u need to agree to a license

2020-06-20 15:48 UTC, n3roxis approved these changes

2020-06-20 16:05 UTC, merged