Allow visual debugging from any thread
FAForever/Neroxis-Map-Generator pull request #412
Opened 2024-08-01 15:54 UTC by clivepaterson

This is a small change to make the Visual Debugger work when generating a map.
When doing Swing UI updates, it must be run from the UI thread.
So this uses `SwingUtilities.invokeLater()` to make sure UI updates are run from the UI thread.

Which is nice because we can reliably debug the entire map generation if desired:
EG: this works now without issue:
![image](https://github.com/user-attachments/assets/fbd11b1b-6d87-413f-bb6e-d0639092165a)

2024-08-16 00:32 UTC, Sheikah45 commented
Sorry  missed the notification on this. This is actually interesting I wasn't aware that the UI updates had to be from a specific thread. I am curious now how the visual debugger worked at all previously now haha

2024-08-16 00:34 UTC, Sheikah45 requested changes

2024-08-16 00:34 UTC, Sheikah45 commented on shared/src/main/java/com/faforever/neroxis/visualization/VisualDebugger.java
> +        );
```suggestion
        SwingUtilities.invokeLater(() -> {
                        createGui();
                        String name = copyOfmask.getVisualName();
                        name = name == null ? copyOfmask.getName() : name;
                        updateList(name + " " + method + " " + line, copyOfmask.immutableCopy());
                    });
```

2024-08-16 08:28 UTC, clivepaterson commented
> Sorry missed the notification on this. This is actually interesting I wasn't aware that the UI updates had to be from a specific thread. I am curious now how the visual debugger worked at all previously now haha

Yeah it's an interesting one... It does work fine using the TestingGround.. because it's single threaded.

I've only come accross this once before many years ago when I was making a Plugin for Outlook using C#...
I was running into this UI thread challenge, I think in that case I was able to use 'Thread.join()'  to get back onto the main UI thread...

I guess it's hard to make a UI framework completely thread safe...
But I think SwingUtilities.invokeLater() is an accepted / conventient Java/Swing way to get code running back on the UI thread which I think is always the main thread.

2024-08-16 16:18 UTC, Sheikah45 commented
I think there is a semi colon missing. Once added and tests pass I can merge.

2024-08-17 07:49 UTC, Sheikah45 approved these changes

2024-08-17 07:49 UTC, merged

2024-08-17 16:32 UTC, Sheikah45 commented
Ah yes this is much nicer know. I had always meant to figure out why sometimes the UI bugged out when run with --visualize. Thanks!